<?php
/**
 * @file
 * Code for the camp features feature.
 */

include_once 'camp_features.features.inc';

function camp_features_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form ['type']) && $form ['type']['#value'] == "camp_features") {
    $form['actions']['submit']['#submit'][]='my_callback_function';
    $form['#validate'][] = 'starting_drupal_dev_form_validate';
    dpm($form);
 }
}

function my_callback_function($form,$form_state) {
  drupal_set_message('<p>Do something before submit!</p>');
}

function starting_drupal_dev_form_validate ($form, &$form_state) {
  drupal_set_message('<p>Do some validation!</p>');
}
